In [1]:
import numpy as np

In [2]:
arr = np.array([2,3,45,6,77,888888])
print(arr)

[     2      3     45      6     77 888888]


In [3]:
arr1 = np.array([[1,2,30],[20,3,1]])
arr1

array([[ 1,  2, 30],
       [20,  3,  1]])

In [9]:
arr2 = np.array([[1,2,3],[2,34,5],[5,6,7]])
arr2
print(arr2.shape)
print(type(arr2))

(3, 3)
<class 'numpy.ndarray'>


In [ ]:
#Creating Arrays from Scratch:

In [11]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
np.full((2,4), 11)

array([[11, 11, 11, 11],
       [11, 11, 11, 11]])

In [21]:
np.arange(2,100,5)                                                  #2+5 = 7, 7+5= 12 and so on till 99

array([ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47, 52, 57, 62, 67, 72, 77, 82,
       87, 92, 97])

In [25]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [28]:
w = np.array([[20,30,40],[12,22,33],[45,46,37],[6,0,6]])
w

array([[20, 30, 40],
       [12, 22, 33],
       [45, 46, 37],
       [ 6,  0,  6]])

In [33]:
w.shape   #op- (4, 3)

(4, 3)

In [34]:
w.size       #op- 12

12

In [35]:
w.ndim               #op- 2

2

In [36]:
w.dtype         #op- dtype('int64')

dtype('int64')

In [39]:
#Changing Data Types

a1 = np.array([1,2,3,4,5,6], dtype= np.float32)                    #op- array([1., 2., 3., 4., 5., 6.], dtype=float32)
a1

array([1., 2., 3., 4., 5., 6.], dtype=float32)

In [42]:
b1 = np.array([[3,4,5],[7,8,9]])
b1

array([[3, 4, 5],
       [7, 8, 9]])

In [43]:
print(b1.reshape(3,2))        

[[3 4]
 [5 7]
 [8 9]]


In [44]:
# Convert 2D → 1D

c1 = np.array([[45,6,7,7],[11,22,33,44]])
c1

array([[45,  6,  7,  7],
       [11, 22, 33, 44]])

In [48]:
print(c1.flatten())                             #op-  [45  6  7  7 11 22 33 44]

[45  6  7  7 11 22 33 44]
