In [1]:
import numpy as np

In [2]:
arr = np.array([10, 20, 30, 40,50,70,39,67])


In [3]:
print(arr[2])

30


In [4]:
print(arr[-4])

50


In [5]:
print(arr[0:2])

[10 20]


In [6]:
print(arr[:3])

[10 20 30]


In [7]:
print(arr[::2])

[10 30 50 39]


In [18]:
s = arr[2:5]
arr[2]= 23
s.copy()

array([23, 40, 23])

In [19]:
arr

array([10, 20, 23, 40, 23, 70, 39, 67])

In [ ]:
#Fancy Indexing (Select Multiple Elements)

In [21]:
s1= np.array([23,4,3,3344,5556,777,23,666,34])

In [25]:
idx = [3,5,7]
print(s1[idx])

[3344  777  666]


In [ ]:
#Boolean Masking (Filter Data) - codinational values

In [28]:
arr3 = np.array([10, 20, 30, 40, 50])
arr3[arr3>23] 

array([30, 40, 50])