In [ ]:
                                                #understanding how to work with axis 

In [1]:
import numpy as np

In [2]:
arr = np.array([[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])

In [4]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
arr[0]

array([1, 2, 3])

In [10]:
np.sum(arr, axis=0)

array([12, 15, 18])

In [12]:
np.sum(arr, axis=1)

array([ 6, 15, 24])

In [14]:
arr[2]

array([7, 8, 9])

In [ ]:
                                                     #Indexing in Multidimensional Arrays

In [16]:
arr[1, 2]

np.int64(6)

In [17]:
arr[0][1]

np.int64(2)

In [18]:
arr[0][2]

np.int64(3)

In [22]:
arr[1][2]

np.int64(6)

In [28]:
arr[0:2, 1:3]

array([[2, 3],
       [5, 6]])

In [33]:
arr[0:4, 1:4]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [35]:
arr[1:2, 1:3]

array([[5, 6]])

In [37]:
arr[0:2, 1:2]

array([[2],
       [5]])

In [41]:
arr[1:3, 0:2]

array([[4, 5],
       [7, 8]])

In [42]:
arr[0:2, 0:2]

array([[1, 2],
       [4, 5]])

In [43]:
arr1 = np.array([[11,22,33],
               [44,55,66],
               [77,88,99],
               [111,222,333]])

In [45]:
arr1[1:3, 1:3]

array([[55, 66],
       [88, 99]])

In [46]:
arr1[2:4, 0:2]

array([[ 77,  88],
       [111, 222]])

In [48]:
arr1[0:2, 1:3]

array([[22, 33],
       [55, 66]])

In [49]:
arr1[0:2, 0:2]

array([[11, 22],
       [44, 55]])

In [52]:
arr1[1:3, 0:2]

array([[44, 55],
       [77, 88]])

In [53]:
arr1[2:4, 0:2]

array([[ 77,  88],
       [111, 222]])